INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('ADM', '광고 상태 발송 코드', 1, 26);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('ADT', '광고 심사상태 코드', 1, 11);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('AFT', '광고 업로드 파일 종류', 1, 12);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BCT', '사업자구분 코드', 1, 20);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BDG', '배지 코드', 1, 5);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BDT', '하단 화면 타입 코드( 배너 등)', 1, 10);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BLT', 'WEB 배너 위치(상단, 하단, 우측 등)', 1, 34);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BNT', '배너 타입 코드', 1, 10);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('BST', '업종 코드', 1, 13);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('CTS', '고객 상태 코드', 1, 1);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('CUT', '쿠폰 사용여부', 1, 29);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DCL', '디바이스 컨텐츠 로그 등급', 1, 36);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DCS', '디바이스 화면 위치(screen_pos_main,screen_pos_left,screen_pos_bottom)', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DCT', '디바이스 시스템검출 코드', 1, 33);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DDT', '디바이스 심각 상태코드', 1, 40);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DLT', '디바이스 상태 등급(정상, 주의, 심각 등)', 1, 38);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DPD', '화면 분할 코드(전체, 2분할, 3분할 등)', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DSC', '화면 서비스 코드(video, 날씨, 배너 등)', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DSI', '디바이스 상태 정보 (start,resume,pause,stop,destroy)', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DSL', '디바이스 상태 로그 등급', 1, 37);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DSS', '화면 구분 코드(main, side, top, bottom 등)', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DST', '광고 디자인 요청 코드', 1, 19);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DUS', '미세 먼지 등급 코드', 1, 9);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('DVT', '디바이스 타입 코드(크롬, TCL 등)', 1, 7);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('FCM', '디바이스 PUSH 로 APP 상태 제어코드', 1, 8);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('IPT', '결제 구분(결제, 취소)', 1, 39);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('IQT', '1:1문의 문의유형', 1, 14);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('MCT', '가입자 프로모션 사용기한코드(첫결제시, 가입후)', 1, 30);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('MSC', '관리자 상태 코드', 1, 2);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('MST', '메세지 발송구분', 1, 31);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('MTC', '메세지 타입구분', 1, 32);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('NAT', '문자 발송 타입(자동, 수동)', 1, 35);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('NTC', '알림 타켓 코드', 1, 25);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('OPT', '운영여부', 1, 21);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('PDT', '프로모션 할인종류', 1, 28);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('PGS', '페이징사이즈', 1, 3);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('PGT', '광고 진행상태 코드', 1, 16);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('PTC', '프로모션 종류', 1, 27);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('PTT', '파트너 타입 코드', 1, 6);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('RJT', '광고 보류타입 코드', 1, 15);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('RPT', '1:1문의 답변 여부 코드', 1, 17);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('SHO', 'FAQ 전시여부 코드', 1, 18);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('SLT', '지하철 노선 코드', 1, 23);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('TRM', '약관 종류', 1, 4);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('TST', '약관 상태', 1, 4);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('UST', '노출여부', 1, 22);
INSERT INTO oddi.code_group (code, name, usable, ordering) VALUES ('WTR', '날씨 코드', 1, 9);
