INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADM001', 'ADM', '대기', 1, 10, null, 'SCHEDULER');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADM002', 'ADM', '승인 발송', 1, 20, null, 'SCHEDULER');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADM003', 'ADM', '보류 발송', 1, 30, null, 'SCHEDULER');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADM004', 'ADM', '종료 예정 발송', 1, 40, null, 'SCHEDULER');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADT001', 'ADT', '대기', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADT002', 'ADT', '승인', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('ADT003', 'ADT', '보류', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('AFT001', 'AFT', '이미지', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('AFT002', 'AFT', '동영상', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('AFT003', 'AFT', '프로모타', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BCT001', 'BCT', '법인사업자', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BCT002', 'BCT', '개인사업자', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BCT003', 'BCT', '개인', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BDG001', 'BDG', '완판', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BDG002', 'BDG', '마감임박', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BDG003', 'BDG', 'HOT', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BDT001', 'BDT', '배너', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BLT001', 'BLT', '상단', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BLT002', 'BLT', '하단', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BLT003', 'BLT', '우측', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BLT004', 'BLT', '팝업', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BNT001', 'BNT', 'Web', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BNT002', 'BNT', 'Device', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST001', 'BST', '농업, 임업 및 어업', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST002', 'BST', '제조업', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST003', 'BST', '건설업', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST004', 'BST', '도매 및 소매업', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST005', 'BST', '운수 및 창고업', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST006', 'BST', '숙박', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST007', 'BST', '음식점업', 1, 70, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST008', 'BST', '정보통신업', 1, 80, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST009', 'BST', '금융 및 보험업', 1, 90, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST010', 'BST', '부동산업', 1, 100, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST011', 'BST', '사업시설 관리, 사업 지원 및 임대 서비스업', 1, 110, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST012', 'BST', '교육서비스', 1, 120, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST013', 'BST', '보건업 및 사회복지 서비스업', 1, 130, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST014', 'BST', '예술, 스포츠 및 여가관련 서비스업', 1, 140, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST015', 'BST', '협회 및 단체,국제 및 외국기관', 1, 150, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('BST016', 'BST', '기타', 1, 160, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CTS001', 'CTS', '정상', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CTS002', 'CTS', '정지', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CTS003', 'CTS', '비밀번호오류', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CTS004', 'CTS', '휴면', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CTS005', 'CTS', '탈퇴', 0, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CUT001', 'CUT', '사용', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('CUT002', 'CUT', '미사용', 1, 20, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCL001', 'DCL', '재생시작', 1, 10, 'start', 'DLT001');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCL002', 'DCL', '재생중 오류', 1, 20, 'error', 'DLT002');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT001', 'DCT', 'main광고 재생실패', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT002', 'DCT', '앱 백그라운드(5분)', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT003', 'DCT', '앱 중지(5분)', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT004', 'DCT', '앱 구동 실패', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT005', 'DCT', '앱 반복 종료', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DCT006', 'DCT', '앱 종료 유지', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT001', 'DDT', 'main 광고 재생 실패', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT002', 'DDT', '앱 백그라운드(5분)', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT003', 'DDT', '앱 중지(5분)', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT004', 'DDT', '앱 구동 실패', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT005', 'DDT', '앱 반복 종료', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DDT006', 'DDT', '앱 종료 유지', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DLT001', 'DLT', '정상', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DLT002', 'DLT', '주의', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DLT003', 'DLT', '심각', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL001', 'DSL', '앱 시작', 1, 10, 'start', 'DLT001');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL002', 'DSL', '화면 가림', 1, 20, 'pause', 'DLT002');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL003', 'DSL', '백그라운드', 1, 30, 'stop', 'DLT002');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL004', 'DSL', '포그라운드', 1, 40, 'resume', 'DLT001');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL005', 'DSL', '광고시작', 1, 50, 'run', 'DLT001');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL006', 'DSL', '사용자 종료', 1, 60, 'destory_user', 'DLT002');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL007', 'DSL', '앱 종료', 1, 70, 'destory_exception', 'DLT002');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSL008', 'DSL', '오류 발생', 1, 80, 'exception', 'DLT003');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DSS004', 'DSS', 'top', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DST001', 'DST', '요청', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DST002', 'DST', '직접제작', 1, 10, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DUS001', 'DUS', '좋음', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DUS002', 'DUS', '보통', 1, 20, '2', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DUS003', 'DUS', '나쁨', 1, 30, '3', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DUS004', 'DUS', '매우나쁨', 1, 40, '4', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DVT001', 'DVT', '크롬캐스트', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('DVT002', 'DVT', 'TCL', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IPT001', 'IPT', '결제', 1, 10, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IPT002', 'IPT', '취소', 1, 20, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IQT001', 'IQT', '회원계정관련', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IQT002', 'IQT', '광고신청관련', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IQT003', 'IQT', '심사관련', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IQT004', 'IQT', '결제관련', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('IQT005', 'IQT', '기타관련', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MCT001', 'MCT', '첫결제시', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MCT002', 'MCT', '가입후', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MSC001', 'MSC', '사용', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MSC002', 'MSC', '정지', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MSC003', 'MSC', '휴면', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MST001', 'MST', '즉시', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MST002', 'MST', '예약', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MTC001', 'MTC', '광고성(광고수신 거부자 제외)', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('MTC002', 'MTC', '정보성', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NAT001', 'NAT', '자동', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NAT002', 'NAT', '수동', 1, 20, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC001', 'NTC', '전체 회원', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC002', 'NTC', '전체 광고주', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC003', 'NTC', '전체 오디존 광고주', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC004', 'NTC', '전체 지하철 광고주', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC005', 'NTC', '오디존 광고주', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC006', 'NTC', '지하철 광고주', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC007', 'NTC', '회원 검색', 1, 70, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('NTC008', 'NTC', '전화번호 입력', 1, 80, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('OPT001', 'OPT', '운영', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('OPT002', 'OPT', '미운영', 1, 20, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PDT001', 'PDT', '정액', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGS001', 'PGS', '사용', 1, 10, '10', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGS002', 'PGS', '사용', 1, 20, '20', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGS003', 'PGS', '사용', 1, 30, '30', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGS004', 'PGS', '사용', 1, 40, '50', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGS005', 'PGS', '사용', 1, 50, '100', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGT001', 'PGT', '신청', 1, 10, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGT002', 'PGT', '결제 완료', 1, 20, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGT003', 'PGT', '결제 실패', 1, 30, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGT004', 'PGT', '결제 취소', 1, 40, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PGT005', 'PGT', '신청 취소', 1, 50, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PTC001', 'PTC', '가입', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PTC002', 'PTC', '일반', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PTT001', 'PTT', '오디존', 1, 10, null, '1');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PTT002', 'PTT', '지하철', 1, 20, null, '1');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('PTT003', 'PTT', '파트너신청', 0, 30, null, '0');
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('RJT001', 'RJT', '컨텐츠', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('RJT002', 'RJT', '사업자정보', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('RJT003', 'RJT', '기타', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('RPT001', 'RPT', '답변대기', 1, 10, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('RPT002', 'RPT', '답변완료', 1, 20, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SHO001', 'SHO', '전시', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SHO002', 'SHO', '숨김', 1, 10, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT001', 'SLT', '1호선', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT002', 'SLT', '2호선', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT003', 'SLT', '3호선', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT004', 'SLT', '4호선', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT005', 'SLT', '5호선', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT006', 'SLT', '6호선', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT007', 'SLT', '7호선', 1, 70, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT008', 'SLT', '8호선', 1, 80, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT009', 'SLT', '9호선', 1, 90, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT010', 'SLT', '인천1호선', 1, 100, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT011', 'SLT', '인천2호선', 1, 110, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT012', 'SLT', '신분당', 1, 120, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT013', 'SLT', '경의중앙선', 1, 130, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT014', 'SLT', '경춘선', 1, 140, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT015', 'SLT', '수인분당', 1, 150, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT016', 'SLT', '공항', 1, 160, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT017', 'SLT', '의정부', 1, 170, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT018', 'SLT', '에버라인', 1, 180, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT019', 'SLT', '자기부상', 1, 190, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT020', 'SLT', '경강선', 1, 200, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT021', 'SLT', '우이신설', 1, 210, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT022', 'SLT', '서해선', 1, 220, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('SLT023', 'SLT', '김포골드', 1, 230, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TRM001', 'TRM', '서비스 이용 약관', 1, 1, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TRM002', 'TRM', '개인정보 처리방침', 1, 1, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TRM003', 'TRM', '제3자 정보제공 이용동의', 1, 1, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TRM004', 'TRM', '개인정보 마케팅이용 수집 및 동의', 1, 1, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TRM005', 'TRM', '광고 신청 약관', 1, 1, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TST001', 'TST', '임시저장', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TST002', 'TST', '사용', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('TST003', 'TST', '폐기', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('UST001', 'UST', '노출', 1, 10, '1', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('UST002', 'UST', '비노출', 1, 20, '0', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR001', 'WTR', '맑음', 1, 10, 'ico_w01', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR002', 'WTR', '구름조금', 1, 10, 'ico_w02', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR003', 'WTR', '구름많음', 1, 20, 'ico_w03', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR004', 'WTR', '흐림', 1, 30, 'ico_w04', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR005', 'WTR', '비', 1, 40, 'ico_w05', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('WTR006', 'WTR', '눈', 1, 50, 'ico_w06', null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('bottom', 'DSS', 'bottom', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('destroy', 'DSI', '광고 APP 이 종료된 상태', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('device_create', 'FCM', '디바이스 생성 성공으로 다음광고 화면 으로 진행요청  ', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('divisions_1', 'DPD', '전체', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('divisions_2', 'DPD', '2분할', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('divisions_3', 'DPD', '3분할', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('finish_app', 'FCM', 'APP 종료처리  ', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('image', 'DSC', '배너', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('main', 'DSS', 'main', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('pause', 'DSI', '광고 화면이 무언가에 의해 일부분이 가려진 상태', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('request_bottom_ad', 'FCM', '하단 배너 광고 리스트 변경알림 ', 1, 60, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('request_main_ad', 'FCM', '메인 광고 리스트 변경알림', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('request_side_ad', 'FCM', '오른쪽 배너 광고 리스트 변경알림 ', 1, 50, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('restart_app', 'FCM', 'APP 재시작처리 ', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('resume', 'DSI', '광고 화면이 활성화 되어 광고를 시작 하는 상태', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('screen_pos_bottom', 'DCS', '화면 하단', 1, 30, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('screen_pos_main', 'DCS', '화면메인', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('screen_pos_side', 'DCS', '화면 사이드', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('set_ad_screen_type', 'FCM', '화면 분할을 강제 변경 알림 ', 1, 70, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('side', 'DSS', 'side', 1, 20, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('start', 'DSI', '광고 화면의 첫 시작을 알림', 1, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('stop', 'DSI', '광고 화면의 전체가 사라진 상태', 1, 40, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('video', 'DSC', 'video', 0, 10, null, null);
INSERT INTO oddi.code (code, group_code, name, usable, ordering, val, using_type) VALUES ('weather', 'DSC', '날씨', 1, 20, null, null);
