INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('ADP001', 'ADP', '오디존', null, '/adv/place/oddizone', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('ADP002', 'ADP', '지하철', null, '/adv/place/subwayzone', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('ADV001', 'ADV', '광고 심사', null, '/adv/judge', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('ADV002', 'ADV', '광고 편성', null, '/advertisement/plan', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('BLL001', 'BLL', '광고 내역', null, '/sales/advhistory', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('BLL002', 'BLL', '결제 내역', null, '/sales/payment', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CNT001', 'CNT', '라이브스트림', null, '/advertisement/content/livestream', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CNT002', 'CNT', '광고판 우측 배너', null, '/advertisement/content/envrightbanner', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CNT003', 'CNT', '광고판 하단 배너', null, '/advertisement/content/envbottombanner', 1, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CNT004', 'CNT', '사이트 상단 배너', null, '/advertisement/content/sitetopbanner', 1, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CNT005', 'CNT', '사이트 팝업', null, '/advertisement/content/sitepopup', 1, 50);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('COS001', 'COS', '공지사항', null, '/customer/service/notice', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('COS002', 'COS', '1:1문의', null, '/customer/service/qna', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('COS003', 'COS', 'FAQ', null, '/customer/service/faq', 1, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('COS004', 'COS', '파트너 문의', null, '/customer/service/partner-qna', 1, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('CST001', 'CST', '회원관리', null, '/customer/member', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('DSH001', 'DSH', '대시보드', null, null, 0, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('DVC001', 'DVC', '기기관리', null, '/environment', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('MNG001', 'MNG', '관리자 계정', null, '/admin/account', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('MNG002', 'MNG', '관리자 그룹', null, '/admin/group', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('NTF001', 'NTF', '문자메세지 발송', null, '/message/send', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('NTF002', 'NTF', '이메일 발송', null, null, 0, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('NTF003', 'NTF', '문자메세지 발송 내역', null, '/message/hist', 1, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('NTF004', 'NTF', '이메일 발송 내역', null, null, 0, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('PRD001', 'PRD', '묶음 상품 관리', null, '/purchase/bundlepurchase', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('PRD002', 'PRD', '오디존 상품 설정', null, '/purchase/oddizone/config', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('PRD003', 'PRD', '지하철 상품 설정', null, '/purchase/subwayzone/config', 1, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('PRD004', 'PRD', '프로모션 관리', null, '/purchase/promotion', 1, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT001', 'STT', '매출 통계', null, null, 0, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT002', 'STT', '상품 통계', null, null, 0, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT003', 'STT', '가입자 통계', null, null, 0, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT004', 'STT', '광고 노출 통계', null, null, 0, 50);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT005', 'STT', '오디존 통계', null, null, 0, 60);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('STT006', 'STT', '기기 상태 통계', null, null, 0, 70);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('TRM001', 'TRM', '서비스 이용 약관', null, '/clause/service', 1, 10);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('TRM002', 'TRM', '개인정보 처리방침', null, '/clause/privacy', 1, 20);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('TRM003', 'TRM', '제3자 정보제공', null, '/clause/provide', 1, 30);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('TRM004', 'TRM', '개인정보 마케팅이용', null, '/clause/marketing', 1, 40);
INSERT INTO oddi.menu (id, group_id, menu_name, icon, router_link, usable, ordering) VALUES ('TRM005', 'TRM', '광고 신청 약관', null, '/clause/apply', 1, 50);
